import { useEffect, useState } from "react";
import { Check, Loader, Mail, RefreshCw, ShoppingBag } from "lucide-react";
import toast from "react-hot-toast";
import axios from "../lib/axios";

const RecoveryTab = () => {
  const [settings, setSettings] = useState({ enabled: true, delayHours: 24 });
  const [analytics, setAnalytics] = useState({ sent: 0, recovered: 0, recoveredValue: 0, recoveryRate: 0 });
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  useEffect(() => { axios.get("/recovery/admin").then(({ data }) => { setSettings(data.settings); setAnalytics(data.analytics); }).catch((error) => toast.error(error.response?.data?.message || "Unable to load recovery settings")).finally(() => setLoading(false)); }, []);
  const save = async () => { setSaving(true); try { const { data } = await axios.patch("/recovery/admin", settings); setSettings(data.settings); toast.success(data.message); } catch (error) { toast.error(error.response?.data?.message || "Unable to save settings"); } finally { setSaving(false); } };
  if (loading) return <div className="flex justify-center rounded-2xl bg-white py-20"><Loader className="animate-spin text-[#6f856c]" /></div>;
  return <section className="rounded-2xl border border-[#e1dacb] bg-white p-6 shadow-sm sm:p-8"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="section-kicker text-[#7c9279]">Customer follow-up</p><h2 className="mt-2 font-serif text-3xl text-[#27352b]">Cart recovery</h2><p className="mt-2 max-w-xl text-sm leading-6 text-[#687064]">Send one considerate reminder when a signed-in customer leaves an unchanged cart behind.</p></div><span className={`rounded-full px-4 py-2 text-xs font-bold uppercase ${settings.enabled ? "bg-[#e2eee1] text-[#4d6c53]" : "bg-[#efeee9] text-[#777a75]"}`}>{settings.enabled ? "Active" : "Paused"}</span></div><div className="mt-7 grid gap-4 sm:grid-cols-3"><Metric icon={Mail} label="Emails sent" value={analytics.sent} /><Metric icon={ShoppingBag} label="Recovered orders" value={analytics.recovered} /><Metric icon={RefreshCw} label="Recovery rate" value={`${Number(analytics.recoveryRate).toFixed(1)}%`} /></div><div className="mt-8 grid gap-5 rounded-2xl bg-[#f8f6ef] p-5 md:grid-cols-[1fr_1fr_auto] md:items-end"><label className="flex items-center gap-3 text-sm font-semibold"><input type="checkbox" checked={settings.enabled} onChange={(event) => setSettings({ ...settings, enabled: event.target.checked })} className="h-5 w-5 accent-[#6f856c]" /> Enable recovery emails</label><label className="text-sm font-semibold">Wait before sending<select value={settings.delayHours} onChange={(event) => setSettings({ ...settings, delayHours: Number(event.target.value) })} className="mt-2 w-full rounded-xl border border-[#d8d2c5] bg-white px-4 py-3 font-normal"><option value={1}>1 hour</option><option value={6}>6 hours</option><option value={12}>12 hours</option><option value={24}>24 hours</option><option value={48}>48 hours</option><option value={72}>3 days</option><option value={168}>7 days</option></select></label><button onClick={save} disabled={saving} className="inline-flex items-center justify-center gap-2 rounded-full bg-[#314b3b] px-6 py-3 text-sm font-semibold text-white disabled:opacity-50">{saving ? <Loader size={16} className="animate-spin" /> : <Check size={16} />} Save settings</button></div><p className="mt-5 text-sm text-[#687064]">Recovered revenue in the last 30 days: <strong className="text-[#314b3b]">${Number(analytics.recoveredValue).toFixed(2)}</strong></p></section>;
};
const Metric = ({ icon: Icon, label, value }) => <div className="rounded-2xl border border-[#e5dfd3] p-5"><Icon className="text-[#7c9279]" size={20} /><p className="mt-4 text-3xl font-bold text-[#27352b]">{value}</p><p className="mt-1 text-sm text-[#687064]">{label}</p></div>;
export default RecoveryTab;
