import { useEffect, useMemo, useState } from "react";
import { Check, Loader, Search, ShieldCheck, Star, Trash2, X } from "lucide-react";
import toast from "react-hot-toast";
import axios from "../lib/axios";

const ReviewsTab = () => {
  const [reviews, setReviews] = useState([]);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState("");
  const [view, setView] = useState("pending");
  const [search, setSearch] = useState("");

  const load = async () => { try { const { data } = await axios.get("/products/reviews/admin"); setReviews(data.reviews || []); } catch (error) { toast.error(error.response?.data?.message || "Unable to load reviews"); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const visible = useMemo(() => reviews.filter((review) => (view === "all" || review.status === view) && `${review.productName} ${review.username} ${review.comment}`.toLowerCase().includes(search.toLowerCase())), [reviews, search, view]);
  const counts = reviews.reduce((result, review) => ({ ...result, [review.status]: (result[review.status] || 0) + 1 }), {});

  const moderate = async (review, status) => { setSaving(review._id); try { await axios.patch(`/products/reviews/${review.productId}/${review._id}`, { status, adminNote: review.adminNote || "" }); setReviews((current) => current.map((item) => item._id === review._id ? { ...item, status } : item)); toast.success(`Review ${status}`); } catch (error) { toast.error(error.response?.data?.message || "Unable to update review"); } finally { setSaving(""); } };
  const remove = async (review) => { if (!window.confirm("Delete this review permanently?")) return; setSaving(review._id); try { await axios.delete(`/products/reviews/${review.productId}/${review._id}`); setReviews((current) => current.filter((item) => item._id !== review._id)); toast.success("Review deleted"); } catch (error) { toast.error(error.response?.data?.message || "Unable to delete review"); } finally { setSaving(""); } };

  return <section className="rounded-2xl border border-[#e1dacb] bg-white p-5 shadow-sm sm:p-7">
    <div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><p className="section-kicker text-[#7c9279]">Customer trust</p><h2 className="mt-2 font-serif text-3xl text-[#27352b]">Review moderation</h2><p className="mt-2 text-sm text-[#687064]">Approve verified customer feedback before it appears on product pages.</p></div><label className="relative w-full lg:max-w-xs"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-[#7c9279]" size={17} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search reviews" className="w-full rounded-full border border-[#dcd5c5] py-3 pl-11 pr-4 text-sm outline-none focus:ring-4 focus:ring-[#e6eee3]" /></label></div>
    <div className="mt-6 flex flex-wrap gap-2">{["pending", "approved", "rejected", "all"].map((status) => <button key={status} onClick={() => setView(status)} className={`rounded-full px-4 py-2 text-xs font-bold capitalize ${view === status ? "bg-[#314b3b] text-white" : "bg-[#f1eee6] text-[#687064]"}`}>{status} {status !== "all" && `(${counts[status] || 0})`}</button>)}</div>
    {loading ? <div className="flex justify-center py-20"><Loader className="animate-spin text-[#6f856c]" /></div> : <div className="mt-6 space-y-4">{visible.map((review) => <article key={review._id} className="rounded-2xl border border-[#e5dfd3] p-5"><div className="flex flex-col gap-5 md:flex-row"><img src={review.productImage} alt="" className="h-20 w-20 rounded-xl object-cover" /><div className="min-w-0 flex-1"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold text-[#354139]">{review.productName}</p><p className="mt-1 text-sm text-[#687064]">{review.username}</p></div><span className={`rounded-full px-3 py-1 text-[10px] font-bold uppercase ${review.status === "approved" ? "bg-[#e2eee1] text-[#4d6c53]" : review.status === "rejected" ? "bg-[#f3e2df] text-[#895149]" : "bg-[#f5ead2] text-[#8a6826]"}`}>{review.status}</span></div><div className="mt-3 flex items-center gap-3"><span className="inline-flex">{[1,2,3,4,5].map((star) => <Star key={star} size={15} className={star <= review.rating ? "fill-[#b58a34] text-[#b58a34]" : "text-[#cbc6bb]"} />)}</span>{review.verifiedPurchase && <span className="inline-flex items-center gap-1 text-xs font-semibold text-[#607660]"><ShieldCheck size={14} /> Verified purchase</span>}</div><p className="mt-4 leading-7 text-[#5f6962]">{review.comment}</p><label className="mt-4 block text-xs font-semibold text-[#687064]">Private moderation note<input value={review.adminNote || ""} onChange={(event) => setReviews((current) => current.map((item) => item._id === review._id ? { ...item, adminNote: event.target.value } : item))} maxLength="500" className="mt-2 w-full rounded-xl border border-[#ddd6c8] px-3 py-2 text-sm font-normal" /></label><div className="mt-4 flex flex-wrap gap-2"><button onClick={() => moderate(review, "approved")} disabled={saving === review._id} className="inline-flex items-center gap-1 rounded-full bg-[#314b3b] px-4 py-2 text-xs font-semibold text-white disabled:opacity-50"><Check size={14} /> Approve</button><button onClick={() => moderate(review, "rejected")} disabled={saving === review._id} className="inline-flex items-center gap-1 rounded-full border border-[#b4776e] px-4 py-2 text-xs font-semibold text-[#895149] disabled:opacity-50"><X size={14} /> Reject</button><button onClick={() => remove(review)} disabled={saving === review._id} className="ml-auto inline-flex items-center gap-1 px-3 py-2 text-xs font-semibold text-[#895149]"><Trash2 size={14} /> Delete</button></div></div></div></article>)}{!visible.length && <p className="rounded-2xl border border-dashed border-[#c9cfc5] py-14 text-center text-sm text-[#687064]">No {view === "all" ? "" : view} reviews found.</p>}</div>}
  </section>;
};
export default ReviewsTab;
