import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, Droplets, Leaf, ShieldCheck, ShoppingBag, Sparkles, UserRound, Wind } from "lucide-react";
import { Link } from "react-router-dom";
import ProductCard from "../components/ProductCard";
import { useProductStore } from "../stores/useProductStore";

const rituals = [
  { slug: "mens-beard-oil", label: "Beard oil", eyebrow: "Condition & soften", copy: "Lightweight botanical oils for a softer beard, comfortable skin, and a clean finish.", icon: Droplets, tone: "bg-[#d6c6a9]" },
  { slug: "whipped-butter", label: "Whipped butter", eyebrow: "Daily moisture", copy: "Rich, fast-melting moisture made for dry hands, elbows, and everyday full-body care.", icon: Leaf, tone: "bg-[#aeb9a6]" },
  { slug: "mens-massage-oil", label: "Massage oil", eyebrow: "Recover & reset", copy: "A smooth botanical blend created for post-workout recovery and a slower end to the day.", icon: Wind, tone: "bg-[#b08c70]" },
];

const BotaniMenPage = () => {
  const { fetchProductsByBrand, products, loading } = useProductStore();
  const [active, setActive] = useState("all");
  useEffect(() => { fetchProductsByBrand("botani-eve"); }, [fetchProductsByBrand]);
  const visibleProducts = useMemo(() => {
    const allowed = new Set(["men", "mens-beard-oil", "whipped-butter", "mens-whipped-butter", "mens-massage-oil"]);
    return products.filter((product) => active === "all" ? allowed.has(product.category) : active === "whipped-butter" ? ["whipped-butter", "mens-whipped-butter"].includes(product.category) : product.category === active);
  }, [active, products]);
  const choose = (slug) => { setActive(slug); document.querySelector("#mens-products")?.scrollIntoView({ behavior: "smooth" }); };

  return <main className="min-h-screen bg-[#f1eee6] text-[#202b25]">
    <p className="bg-[#1f3028] px-4 py-2.5 text-center text-[10px] font-semibold uppercase tracking-[0.22em] text-[#edf0e9] sm:text-[11px]">Straightforward botanical care · Free shipping over $75</p>
    <header className="border-b border-[#ccd1c7] bg-[#f8f6ef]/95">
      <div className="mx-auto grid max-w-7xl grid-cols-[3.5rem_1fr_3.5rem] items-center px-4 py-4 sm:grid-cols-[6rem_1fr_6rem] sm:px-8 sm:py-5"><Link to="/brands/botani-eve" className="inline-flex items-center gap-2 justify-self-start text-xs font-bold uppercase tracking-[0.14em] text-[#536258]"><ArrowLeft size={17} /><span className="hidden sm:inline">Botani Eve</span></Link><Link to="/brands/botani-eve" className="justify-self-center whitespace-nowrap text-center"><span className="block font-serif text-2xl font-semibold tracking-[0.08em] text-[#263b31] sm:text-4xl">BOTANI EVE</span><span className="mt-1 block text-[9px] font-semibold uppercase tracking-[0.36em] text-[#718074]">Rooted in ritual</span></Link><div className="flex items-center justify-self-end gap-3 text-[#314b3b]"><Link to="/account" aria-label="Account"><UserRound className="hidden sm:block" size={19} /></Link><Link to="/cart" aria-label="Shopping bag"><ShoppingBag size={19} /></Link></div></div>
      <nav className="botani-nav mx-auto flex max-w-5xl items-center justify-start gap-7 overflow-x-auto px-5 pb-4 text-[11px] font-bold uppercase tracking-[0.15em] text-[#667469] sm:justify-center"><Link to="/brands/botani-eve" className="whitespace-nowrap">Shop all</Link><Link to="/brands/botani-eve/bath-body" className="whitespace-nowrap">Bath &amp; body</Link><Link to="/brands/botani-eve/seasonal" className="whitespace-nowrap">Seasonal</Link><span className="whitespace-nowrap border-b border-[#263b31] pb-1 text-[#263b31]">Men</span><Link to="/brands/botani-eve/baby" className="whitespace-nowrap">Baby</Link><Link to="/brands/botani-eve/lip-gloss" className="whitespace-nowrap">Lip gloss</Link><Link to="/brands/botani-eve/home-scents" className="whitespace-nowrap">Home scents</Link></nav>
    </header>

    <section className="relative isolate overflow-hidden bg-[#293b32] text-[#f5f1e7]">
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_78%_22%,rgba(189,166,120,0.2),transparent_30%),linear-gradient(120deg,rgba(255,255,255,0.04),transparent_55%)]" />
      <div className="relative mx-auto grid max-w-7xl md:min-h-[620px] md:grid-cols-[0.95fr_1.05fr]">
        <div className="z-10 flex items-center px-6 py-16 sm:px-12 sm:py-20 lg:px-20"><div><div className="inline-flex items-center gap-2 rounded-full border border-[#d1bd91]/35 bg-white/5 px-4 py-2 text-[10px] font-bold uppercase tracking-[0.2em] text-[#d7c69f]"><Sparkles size={14} /> Botani Eve for men</div><h1 className="mt-7 max-w-xl font-serif text-5xl leading-[0.96] tracking-[-0.035em] sm:text-7xl">Simple care.<br /><em className="font-normal text-[#c8ad78]">Grounded confidence.</em></h1><p className="mt-7 max-w-lg text-base leading-7 text-[#cbd4cc] sm:text-lg">No complicated routine. Just considered essentials that condition, soften, and restore—from beard care to full-body moisture.</p><a href="#mens-products" className="mt-9 inline-flex items-center gap-3 rounded-full bg-[#c3a66d] px-7 py-3.5 text-sm font-semibold text-[#1f3028] transition hover:-translate-y-0.5 hover:bg-[#d3bb89]">Shop men’s care <ArrowRight size={17} /></a></div></div>
        <div className="relative min-h-[390px] overflow-hidden sm:min-h-[460px] md:min-h-full" aria-label="Botani Eve men's botanical care"><div className="absolute left-[12%] top-[12%] h-64 w-64 rounded-full border border-[#d1bd91]/20" /><Leaf className="absolute -right-10 top-[5%] h-64 w-64 rotate-[38deg] text-[#71806d]/45" strokeWidth={0.6} /><div className="absolute bottom-[12%] left-[12%] right-[8%] h-16 rounded-[50%] bg-black/30 blur-xl" /><div className="absolute bottom-[18%] left-[15%] z-10 flex h-44 w-32 -rotate-3 items-center justify-center rounded-[1.4rem] bg-gradient-to-r from-[#947752] to-[#c1a473] shadow-2xl"><div className="text-center text-[#24332b]"><span className="font-serif text-lg">BOTANI EVE</span><small className="mt-3 block text-[7px] font-bold tracking-[0.18em]">BEARD OIL</small></div></div><div className="absolute bottom-[17%] left-[43%] z-20 flex h-64 w-40 rotate-2 items-center justify-center rounded-[2rem] bg-gradient-to-r from-[#d9d2bf] to-[#aeb7a6] shadow-2xl"><div className="border border-[#405247]/30 px-5 py-9 text-center text-[#293b32]"><span className="font-serif text-xl leading-none">BOTANI<br />EVE</span><small className="mt-4 block text-[7px] font-bold tracking-[0.18em]">BODY BUTTER</small></div></div><div className="absolute bottom-[18%] right-[7%] z-10 flex h-48 w-28 -rotate-2 items-center justify-center rounded-[1.3rem] bg-[#755b47] shadow-2xl"><div className="text-center text-[#efe5d2]"><span className="font-serif text-base">BOTANI EVE</span><small className="mt-3 block text-[7px] font-bold tracking-[0.16em]">MASSAGE OIL</small></div></div></div>
      </div>
    </section>

    <section className="border-b border-[#ccd1c7] bg-[#faf8f2]"><div className="mx-auto grid max-w-7xl divide-y divide-[#d7dbd2] px-5 py-5 text-center sm:grid-cols-3 sm:divide-x sm:divide-y-0 sm:px-8"><div className="px-5 py-3"><Leaf className="mx-auto text-[#667865]" size={19} /><p className="mt-2 text-xs font-bold uppercase tracking-[0.17em]">Botanical essentials</p><p className="mt-1 text-sm text-[#737d74]">Plant-forward everyday care</p></div><div className="px-5 py-3"><ShieldCheck className="mx-auto text-[#667865]" size={19} /><p className="mt-2 text-xs font-bold uppercase tracking-[0.17em]">No-fuss routine</p><p className="mt-1 text-sm text-[#737d74]">Simple products that work hard</p></div><div className="px-5 py-3"><Droplets className="mx-auto text-[#667865]" size={19} /><p className="mt-2 text-xs font-bold uppercase tracking-[0.17em]">Comfort first</p><p className="mt-1 text-sm text-[#737d74]">Condition without heaviness</p></div></div></section>

    <section className="mx-auto max-w-7xl px-5 py-16 sm:px-8 lg:py-24"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.24em] text-[#71806f]">Build the routine</p><h2 className="mt-3 font-serif text-4xl sm:text-5xl">Three essentials. Your pace.</h2></div><p className="max-w-sm text-sm leading-6 text-[#687168]">Start with what you need today or layer all three into a complete care ritual.</p></div><div className="mt-11 grid gap-5 lg:grid-cols-3">{rituals.map(({ slug, label, eyebrow, copy, icon: Icon, tone }) => <button key={slug} onClick={() => choose(slug)} className={`${tone} group flex min-h-[340px] flex-col rounded-[1.75rem] p-8 text-left transition hover:-translate-y-1 hover:shadow-xl`}><Icon size={36} strokeWidth={1.2} className="text-[#314b3b]" /><div className="mt-auto pt-14"><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#4e6254]">{eyebrow}</p><h3 className="mt-3 font-serif text-3xl">{label}</h3><p className="mt-3 text-sm leading-6 text-[#4f594f]">{copy}</p><span className="mt-6 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[0.14em] text-[#314b3b]">Shop this ritual <ArrowRight size={14} className="transition group-hover:translate-x-1" /></span></div></button>)}</div></section>

    <section id="mens-products" className="border-y border-[#ccd1c7] bg-[#faf8f2] px-5 py-16 sm:px-8 lg:py-24"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.24em] text-[#71806f]">Botani Eve for men</p><h2 className="mt-3 font-serif text-4xl sm:text-5xl">The complete collection</h2></div><p className="max-w-md text-sm leading-6 text-[#687168]">Straightforward formulas for daily care, recovery, and everything between.</p></div><div className="mt-8 flex gap-2 overflow-x-auto pb-3"><Filter active={active === "all"} onClick={() => setActive("all")}>Shop all</Filter>{rituals.map((item) => <Filter key={item.slug} active={active === item.slug} onClick={() => setActive(item.slug)}>{item.label}</Filter>)}</div>{loading ? <div className="mt-9 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{[0,1,2,3].map((item) => <div key={item} className="h-96 animate-pulse rounded-2xl bg-[#dfe4db]" />)}</div> : visibleProducts.length ? <div className="mt-9 grid gap-6 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{visibleProducts.map((product) => <ProductCard key={product._id} product={product} />)}</div> : <div className="mt-9 rounded-[1.75rem] border border-dashed border-[#aeb9aa] bg-[#e9ede5] px-6 py-14 text-center"><Leaf className="mx-auto text-[#667865]" /><h3 className="mt-4 font-serif text-2xl">The next batch is being prepared</h3><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-[#687168]">Men’s products will appear here as soon as they are added in Brand Studio.</p></div>}</div></section>

    <section className="bg-[#1f3028] px-5 py-16 text-center text-[#eef0e9] sm:px-8"><Leaf className="mx-auto text-[#c3a66d]" strokeWidth={1.2} /><p className="mt-5 text-xs font-bold uppercase tracking-[0.24em] text-[#b9c5ba]">Care without complication</p><h2 className="mx-auto mt-3 max-w-2xl font-serif text-3xl sm:text-4xl">A few good essentials. A routine that feels like your own.</h2></section>
  </main>;
};

const Filter = ({ active, onClick, children }) => <button onClick={onClick} className={`shrink-0 rounded-full border px-4 py-2 text-sm font-semibold transition ${active ? "border-[#293b32] bg-[#293b32] text-white" : "border-[#c6cec3] bg-white text-[#506055] hover:border-[#71806f]"}`}>{children}</button>;
export default BotaniMenPage;
