import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, Droplets, Flower2, Heart, Leaf, ShoppingBag, Sparkles, Star, Sun, UserRound } from "lucide-react";
import { Link } from "react-router-dom";
import ProductCard from "../components/ProductCard";
import { useProductStore } from "../stores/useProductStore";

const glossEdits = [
  { slug: "lip-gloss", label: "The originals", eyebrow: "Everyday shine", copy: "Easy, wearable glosses made to live in your bag and finish every look with comfortable shine.", icon: Heart, tone: "bg-[#ead8d5]" },
  { slug: "seasonal-lip-gloss", label: "Seasonal shades", eyebrow: "Limited edition", copy: "Small-batch colors inspired by the moment—playful, polished, and only here for a little while.", icon: Sparkles, tone: "bg-[#e7d7e2]" },
];

const BotaniLipGlossPage = () => {
  const { fetchProductsByBrand, products, loading } = useProductStore();
  const [active, setActive] = useState("all");
  useEffect(() => { fetchProductsByBrand("botani-eve"); }, [fetchProductsByBrand]);
  const visibleProducts = useMemo(() => products.filter((product) => active === "all" ? ["lip-gloss", "seasonal-lip-gloss"].includes(product.category) : product.category === active), [active, products]);
  const choose = (slug) => { setActive(slug); document.querySelector("#gloss-products")?.scrollIntoView({ behavior: "smooth" }); };

  return <main className="min-h-screen bg-[#fffaf8] text-[#3d3032]">
    <p className="bg-[#6e414a] px-4 py-2.5 text-center text-[10px] font-semibold uppercase tracking-[0.22em] text-[#fff8f3] sm:text-[11px]">Botanical comfort · Effortless shine · Limited seasonal shades</p>
    <header className="border-b border-[#eadbd8] bg-[#fffdfb]/95">
      <div className="mx-auto grid max-w-7xl grid-cols-[3.5rem_1fr_3.5rem] items-center px-4 py-4 sm:grid-cols-[6rem_1fr_6rem] sm:px-8 sm:py-5"><Link to="/brands/botani-eve" className="inline-flex items-center gap-2 justify-self-start text-xs font-bold uppercase tracking-[0.14em] text-[#745b5f]"><ArrowLeft size={17} /><span className="hidden sm:inline">Botani Eve</span></Link><Link to="/brands/botani-eve" className="justify-self-center whitespace-nowrap text-center"><span className="block font-serif text-2xl font-semibold tracking-[0.08em] text-[#56383e] sm:text-4xl">BOTANI EVE</span><span className="mt-1 block text-[9px] font-semibold uppercase tracking-[0.36em] text-[#98767c]">Rooted in ritual</span></Link><div className="flex items-center justify-self-end gap-3 text-[#6e414a]"><Link to="/account" aria-label="Account"><UserRound className="hidden sm:block" size={19} /></Link><Link to="/cart" aria-label="Shopping bag"><ShoppingBag size={19} /></Link></div></div>
      <nav className="botani-nav mx-auto flex max-w-5xl items-center justify-start gap-7 overflow-x-auto px-5 pb-4 text-[11px] font-bold uppercase tracking-[0.15em] text-[#80696d] sm:justify-center"><Link to="/brands/botani-eve" className="whitespace-nowrap">Shop all</Link><Link to="/brands/botani-eve/bath-body" className="whitespace-nowrap">Bath &amp; body</Link><Link to="/brands/botani-eve/seasonal" className="whitespace-nowrap">Seasonal</Link><Link to="/brands/botani-eve/men" className="whitespace-nowrap">Men</Link><Link to="/brands/botani-eve/baby" className="whitespace-nowrap">Baby</Link><span className="whitespace-nowrap border-b border-[#6e414a] pb-1 text-[#6e414a]">Lip gloss</span><Link to="/brands/botani-eve/home-scents" className="whitespace-nowrap">Home scents</Link></nav>
    </header>

    <section className="relative isolate overflow-hidden bg-[#f3e2e0]">
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_20%_20%,rgba(255,255,255,0.9),transparent_30%),radial-gradient(circle_at_80%_70%,rgba(209,157,168,0.35),transparent_34%)]" />
      <div className="relative mx-auto grid max-w-7xl md:min-h-[620px] md:grid-cols-[0.95fr_1.05fr]">
        <div className="z-10 flex items-center px-6 py-16 sm:px-12 sm:py-20 lg:px-20"><div><div className="inline-flex items-center gap-2 rounded-full border border-[#b7848e]/35 bg-white/45 px-4 py-2 text-[10px] font-bold uppercase tracking-[0.2em] text-[#80515a]"><Sparkles size={14} /> The gloss edit</div><h1 className="mt-7 max-w-xl font-serif text-5xl leading-[0.96] tracking-[-0.035em] text-[#56383e] sm:text-7xl">A little color.<br /><em className="font-normal text-[#a15f6c]">A lot of glow.</em></h1><p className="mt-7 max-w-lg text-base leading-7 text-[#725c60] sm:text-lg">Comfortable botanical glosses with a polished finish—from forever favorites to shades made for right now.</p><a href="#gloss-products" className="mt-9 inline-flex items-center gap-3 rounded-full bg-[#6e414a] px-7 py-3.5 text-sm font-semibold text-white transition hover:-translate-y-0.5 hover:bg-[#58333a]">Shop lip gloss <ArrowRight size={17} /></a></div></div>
        <div className="relative min-h-[400px] overflow-hidden sm:min-h-[480px] md:min-h-full" aria-label="Botani Eve lip gloss collection"><div className="absolute left-[12%] top-[10%] h-72 w-72 rounded-full border border-white/60" /><Star className="absolute right-[12%] top-[12%] text-white/80" size={38} strokeWidth={1} /><Flower2 className="absolute -right-12 bottom-[2%] h-64 w-64 text-[#c8939d]/25" strokeWidth={0.7} /><div className="absolute bottom-[13%] left-[12%] right-[9%] h-12 rounded-[50%] bg-[#704650]/20 blur-xl" /><GlossTube className="bottom-[18%] left-[14%] h-52 w-20 -rotate-6 bg-gradient-to-r from-[#d59aa4] to-[#f0c4ca]" label="ROSE" /><GlossTube className="bottom-[17%] left-[40%] z-20 h-72 w-24 rotate-2 bg-gradient-to-r from-[#b45d6e] to-[#db8796]" label="BERRY" /><GlossTube className="bottom-[18%] right-[12%] h-60 w-20 rotate-6 bg-gradient-to-r from-[#c7846f] to-[#e9b09c]" label="NUDE" /></div>
      </div>
    </section>

    <section className="border-y border-[#eadbd8] bg-white"><div className="mx-auto grid max-w-7xl divide-y divide-[#eee1df] px-5 py-5 text-center sm:grid-cols-3 sm:divide-x sm:divide-y-0 sm:px-8"><Promise icon={Droplets} title="Comfortable shine" copy="A smooth finish that feels as good as it looks" /><Promise icon={Leaf} title="Botanical ritual" copy="Thoughtful gloss for effortless everyday wear" /><Promise icon={Sun} title="Made to glow" copy="Wear alone or layer over your favorite color" /></div></section>

    <section className="mx-auto max-w-7xl px-5 py-16 sm:px-8 lg:py-24"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.24em] text-[#a15f6c]">Choose your finish</p><h2 className="mt-3 font-serif text-4xl sm:text-5xl">Your shine, your moment.</h2></div><p className="max-w-sm text-sm leading-6 text-[#75676a]">Stay with a signature favorite or make room for a limited shade inspired by the season.</p></div><div className="mt-11 grid gap-5 md:grid-cols-2">{glossEdits.map(({ slug, label, eyebrow, copy, icon: Icon, tone }) => <button key={slug} onClick={() => choose(slug)} className={`${tone} group flex min-h-[350px] flex-col rounded-[1.75rem] p-8 text-left transition hover:-translate-y-1 hover:shadow-xl`}><Icon size={38} strokeWidth={1.2} className="text-[#80515a]" /><div className="mt-auto pt-16"><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#9a6670]">{eyebrow}</p><h3 className="mt-3 font-serif text-4xl">{label}</h3><p className="mt-3 max-w-lg text-sm leading-6 text-[#6f5b60]">{copy}</p><span className="mt-6 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[0.14em] text-[#6e414a]">Shop the edit <ArrowRight size={14} className="transition group-hover:translate-x-1" /></span></div></button>)}</div></section>

    <section id="gloss-products" className="border-y border-[#eadbd8] bg-[#fdf4f2] px-5 py-16 sm:px-8 lg:py-24"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.24em] text-[#a15f6c]">Botani Eve lip gloss</p><h2 className="mt-3 font-serif text-4xl sm:text-5xl">The complete gloss wardrobe</h2></div><p className="max-w-md text-sm leading-6 text-[#75676a]">Everyday shine and limited seasonal color, all together.</p></div><div className="mt-8 flex gap-2 overflow-x-auto pb-3"><Filter active={active === "all"} onClick={() => setActive("all")}>Shop all gloss</Filter>{glossEdits.map((item) => <Filter key={item.slug} active={active === item.slug} onClick={() => setActive(item.slug)}>{item.label}</Filter>)}</div>{loading ? <div className="mt-9 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{[0,1,2,3].map((item) => <div key={item} className="h-96 animate-pulse rounded-2xl bg-[#ecdeda]" />)}</div> : visibleProducts.length ? <div className="mt-9 grid gap-6 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{visibleProducts.map((product) => <ProductCard key={product._id} product={product} />)}</div> : <div className="mt-9 rounded-[1.75rem] border border-dashed border-[#d2b3b9] bg-white/70 px-6 py-14 text-center"><Sparkles className="mx-auto text-[#a15f6c]" /><h3 className="mt-4 font-serif text-2xl">A fresh gloss drop is coming</h3><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-[#75676a]">Lip gloss products will appear here as soon as they are added in Brand Studio.</p></div>}</div></section>

    <section className="bg-[#6e414a] px-5 py-16 text-center text-[#fff8f3] sm:px-8"><Sparkles className="mx-auto text-[#efc9cf]" strokeWidth={1.2} /><p className="mt-5 text-xs font-bold uppercase tracking-[0.24em] text-[#e8cfd3]">The finishing touch</p><h2 className="mx-auto mt-3 max-w-2xl font-serif text-3xl sm:text-4xl">A swipe of shine. A shade that feels like you.</h2></section>
  </main>;
};

const GlossTube = ({ className, label }) => <div className={`absolute flex items-center justify-center rounded-t-[1.7rem] rounded-b-xl shadow-[0_26px_55px_rgba(88,51,58,0.24)] ${className}`}><div className="absolute -top-7 h-9 w-[72%] rounded-t-lg bg-[#bdaaa6]" /><div className="border border-white/50 px-2 py-7 text-center text-white"><span className="font-serif text-sm">BOTANI EVE</span><small className="mt-3 block text-[7px] font-bold tracking-[0.16em]">{label} GLOSS</small></div></div>;
const Promise = ({ icon: Icon, title, copy }) => <div className="px-5 py-3"><Icon className="mx-auto text-[#a15f6c]" size={19} /><p className="mt-2 text-xs font-bold uppercase tracking-[0.17em]">{title}</p><p className="mt-1 text-sm text-[#807174]">{copy}</p></div>;
const Filter = ({ active, onClick, children }) => <button onClick={onClick} className={`shrink-0 rounded-full border px-4 py-2 text-sm font-semibold transition ${active ? "border-[#6e414a] bg-[#6e414a] text-white" : "border-[#dcc7cb] bg-white text-[#755b60] hover:border-[#a15f6c]"}`}>{children}</button>;

export default BotaniLipGlossPage;
