import { Link, useLocation } from "react-router-dom";

const pages = {
  contact: { eyebrow: "We’re here to help", title: "Contact us", intro: "Questions about a product, order, pickup, or return? Reach out and include your order number when possible.", sections: [["Email", <a className="font-semibold text-[#58715d]" href="mailto:stewarttateandco@gmail.com">stewarttateandco@gmail.com</a>], ["Store & pickup", <>Stewart-Tate &amp; Co.<br />970 N Oak St<br />Jackson, GA 30233<br />Pickup hours: 10 AM–6 PM</>]] },
  shipping: { eyebrow: "Order information", title: "Shipping & local pickup", intro: "Choose standard shipping or free local pickup during checkout.", sections: [["Standard shipping", "Orders under $75 have a $7 shipping charge. Standard shipping is free on orders of $75 or more. The estimated delivery window shown at checkout is 3–5 business days after fulfillment."], ["Local pickup", "Pickup is free at 970 N Oak St, Jackson, GA 30233. Wait until we notify you that your order is ready before arriving. Pickup hours are 10 AM–6 PM."], ["Order tracking", "When tracking is available, it appears in your account and is included in your shipment update email."]] },
  returns: { eyebrow: "Shop with confidence", title: "Returns & refunds", intro: "Return requests are reviewed individually so we can make things right.", sections: [["Requesting a return", <>Sign in, open <Link className="font-semibold text-[#58715d]" to="/orders">Your Orders</Link>, and select “Request a return” on an eligible order. Choose a reason and include helpful details.</>], ["Review process", "We review each request before approving a refund. Items may need to be returned in their original condition, and return instructions will be provided with your decision."], ["Refund timing", "Approved refunds are sent to the original payment method. Your bank or card issuer may take several business days to post the credit. Original shipping charges may not be refundable unless the order arrived damaged or incorrect."], ["Damaged or incorrect items", "Contact us promptly at stewarttateandco@gmail.com with your order number and clear photos so we can help."]] },
  privacy: { eyebrow: "Your information", title: "Privacy policy", intro: "We collect only the information needed to operate the store, fulfill orders, and support customers.", sections: [["Information we use", "This may include your name, email, account details, shipping address, order history, and communications with us."], ["Payments", "Payments are processed by Stripe. Stewart-Tate & Co. does not store your full card number."], ["Service providers", "We may share necessary information with providers that support payments, shipping, email, hosting, database storage, and image hosting. We do not sell personal information."], ["Your choices", "You may contact stewarttateandco@gmail.com to request access, correction, or deletion of personal information, subject to legal and transaction-record requirements."], ["Security & retention", "We use reasonable safeguards and keep information only as long as needed for business, tax, fraud-prevention, and legal purposes."]] },
  terms: { eyebrow: "Store terms", title: "Terms of service", intro: "By using this site or placing an order, you agree to these store terms.", sections: [["Orders", "Product availability and prices may change. We may cancel or limit an order because of inventory errors, suspected fraud, pricing mistakes, or other operational issues; any captured payment for a cancelled order will be refunded."], ["Product information", "We work to present product descriptions, colors, and images accurately, but display settings and handmade or natural product variations may affect appearance."], ["Accounts", "You are responsible for maintaining the confidentiality of your account and for providing accurate, current information."], ["Acceptable use", "Do not misuse the site, attempt unauthorized access, disrupt service, or use store content unlawfully."], ["Liability", "To the extent permitted by law, Stewart-Tate & Co. is not liable for indirect or consequential losses arising from use of the site or products."], ["Contact", "Questions about these terms may be sent to stewarttateandco@gmail.com."]] },
};

const InfoPage = () => {
  const page = pages[useLocation().pathname.slice(1)] || pages.contact;
  return <main className="min-h-[70vh] bg-[#f8f6ef] pb-20"><section className="border-b border-[#ded8ca] bg-[#eef1e8] px-6 py-14"><div className="mx-auto max-w-4xl"><p className="text-xs font-bold uppercase tracking-[0.24em] text-[#78907b]">{page.eyebrow}</p><h1 className="mt-3 font-serif text-4xl text-[#203128] sm:text-6xl">{page.title}</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-[#657168]">{page.intro}</p></div></section><section className="mx-auto max-w-4xl space-y-5 px-6 pt-10">{page.sections.map(([title, content]) => <article key={title} className="rounded-[1.5rem] border border-[#ded8ca] bg-white p-6 shadow-sm sm:p-8"><h2 className="font-serif text-2xl text-[#27352b]">{title}</h2><div className="mt-3 leading-7 text-[#687168]">{content}</div></article>)}<p className="pt-3 text-xs text-[#858c85]">Effective September 27, 2026. Policies may be updated as store operations evolve.</p></section></main>;
};

export default InfoPage;
